import {describe,expect,it} from "vitest";
import sharp from "sharp";
import {inspectPhotoBuffer} from "@/lib/photos/image-validation";
import {assertPhotoAssignmentProject,approvedPhotoConflict,detectImageMime,hasDuplicateContentHash,isSafeZipEntryName,normalizeCanonicalSerial,parsePhotoFilename,proposePhotoMatch,withinPhotoBatchLimits} from "@/lib/photos/matching";
describe("deterministic photo filename matching",()=>{
 it.each([["1.jpg","1"],["001.jpg","001"],["1_Rahul.jpg","1"],["001_Rahul_Sharma.png","001"]])("extracts serial from %s", (filename,serial)=>{const r=parsePhotoFilename(filename);expect(r.status).toBe("EXACT");if(r.status==="EXACT")expect(r.originalSerial).toBe(serial);});
 it("preserves source zero padding but follows integer database canonicalization",()=>{const r=parsePhotoFilename("001.jpg");expect(r.status==="EXACT"&&r.originalSerial).toBe("001");expect(normalizeCanonicalSerial("001")).toBe("1");});
 it("supports prefixed IDs only when configured",()=>{expect(parsePhotoFilename("STU-001.jpg").status).toBe("NEEDS_REVIEW");const r=parsePhotoFilename("STU-001.jpg","STU");expect(r.status).toBe("EXACT");if(r.status==="EXACT")expect(r.normalizedSerial).toBe("1");});
 it("marks ambiguous and unsupported names for review",()=>{expect(parsePhotoFilename("class_5_roll_2.jpg").status).toBe("NEEDS_REVIEW");expect(parsePhotoFilename("photo.jpg").status).toBe("NEEDS_REVIEW");expect(parsePhotoFilename("1_Rahul_2024.jpg").status).toBe("NEEDS_REVIEW");});
 it("never guesses when the student is missing or duplicate",()=>{const m=parsePhotoFilename("8.jpg");expect(proposePhotoMatch(m,[]).status).toBe("UNMATCHED");expect(proposePhotoMatch(m,[{id:"a",serial_number:8},{id:"b",serial_number:8}]).status).toBe("NEEDS_REVIEW");});
 it("detects duplicate content without discarding it",()=>{const r=proposePhotoMatch(parsePhotoFilename("1.jpg"),[{id:"a",serial_number:1}],true);expect(r.status).toBe("DUPLICATE");});
 it("rejects ZIP traversal and unsafe absolute paths",()=>{expect(isSafeZipEntryName("photos/1.jpg")).toBe(true);expect(isSafeZipEntryName("../1.jpg")).toBe(false);expect(isSafeZipEntryName("photos/../../secret")).toBe(false);expect(isSafeZipEntryName("/etc/passwd")).toBe(false);expect(isSafeZipEntryName("C:\\temp\\a.jpg")).toBe(false);});
 it("sniffs supported image signatures instead of trusting MIME labels",()=>{expect(detectImageMime(new Uint8Array([255,216,255,0]))).toBe("image/jpeg");expect(detectImageMime(new Uint8Array([1,2,3]))).toBeNull();});
 it("rejects cross-project assignments",()=>{expect(()=>assertPhotoAssignmentProject("p1","p1","p2")).toThrow("same school project");expect(()=>assertPhotoAssignmentProject("p1","p2","p2")).toThrow();expect(()=>assertPhotoAssignmentProject("p1","p1","p1")).not.toThrow();});
 it("requires explicit confirmation before replacing an approved photo",()=>{expect(approvedPhotoConflict(true,false)).toBe(true);expect(approvedPhotoConflict(true,true)).toBe(false);expect(approvedPhotoConflict(false,false)).toBe(false);});
 it("checks duplicate hashes and enforces file/archive limits",()=>{expect(hasDuplicateContentHash(["abc","def"],"abc")).toBe(true);expect(hasDuplicateContentHash(["abc"],"zzz")).toBe(false);expect(withinPhotoBatchLimits([100,200])).toBe(true);expect(withinPhotoBatchLimits([10*1024*1024+1])).toBe(false);expect(withinPhotoBatchLimits(Array(501).fill(1))).toBe(false);expect(withinPhotoBatchLimits([500*1024*1024,1])).toBe(false);});
 it("decodes valid images and rejects corrupt image payloads",async()=>{const good=await sharp({create:{width:100,height:120,channels:3,background:{r:90,g:120,b:160}}}).jpeg().toBuffer();const verified=await inspectPhotoBuffer(good);expect(verified.mime).toBe("image/jpeg");expect(verified.width).toBe(100);expect(verified.height).toBe(120);expect(verified.errors).toHaveLength(0);const corrupt=await inspectPhotoBuffer(Buffer.from([255,216,255,0,0,0,0,0]));expect(corrupt.errors.length).toBeGreaterThan(0);});
 it("handles a 300-photo matching batch deterministically",()=>{const students=Array.from({length:300},(_,i)=>({id:String(i+1),serial_number:i+1}));const matches=students.map(s=>proposePhotoMatch(parsePhotoFilename(String(s.serial_number).padStart(3,"0")+"_Student.jpg"),students));expect(matches).toHaveLength(300);expect(matches.every((m,i)=>m.status==="MATCHED"&&m.studentId===String(i+1))).toBe(true);});
});
