import { describe, expect, it } from "vitest";
import sharp from "sharp";
import { PDFDocument } from "pdf-lib";
import { physicalPixels, renderIdCard, resolveFieldValue, sanitizeSvg, validateFieldBindings } from "@/lib/rendering/engine";
import type { RenderField, RenderStudent } from "@/lib/rendering/types";

const student:RenderStudent={id:"00000000-0000-4000-8000-000000000001",serial_number:12,data:{student_name:"आरव शर्मा",admission_no:"A-12",class:"VIII"}};
const field=(extra:Partial<RenderField>={}):RenderField=>({id:"f1",key:"student_name",label:"Student name",field_type:"text",required:true,x:5,y:5,width:90,height:24,font_family:"Noto Sans",font_size:14,font_weight:"bold",color:"#123456",alignment:"center",fit_mode:null,source_column:"student_name",render_options:{maxLines:2,wrap:true,overflowPolicy:"warn"},...extra});
async function png(w=100,h=100,color={r:245,g:245,b:245,alpha:1}){return sharp({create:{width:w,height:h,channels:4,background:color}}).png().toBuffer()}
const options={widthMm:25.4,heightMm:25.4,dpi:100,format:"png" as const};
async function render(template:Buffer,fields:RenderField[],overrides:Partial<Parameters<typeof renderIdCard>[0]>={}){return renderIdCard({template,templateType:"image/png",templateId:"tpl-fixture",templateVersion:1,fields,student,schoolName:"Fictional School",photo:null,photoApproved:false,options,...overrides})}
describe("deterministic card renderer",()=>{
 it("converts physical dimensions to pixels and caps unsafe dimensions",()=>{expect(physicalPixels(25.4,300)).toBe(300);expect(()=>physicalPixels(10,30)).toThrow(/DPI/);});
 it("binds values only from explicit mapped columns or configured static values",()=>{expect(resolveFieldValue(field(),student,"School")).toBe("आरव शर्मा");expect(resolveFieldValue(field({source_column:"missing"}),student,"School")).toBeUndefined();expect(resolveFieldValue(field({render_options:{staticValue:"Static"}}),student,"School")).toBe("Static");});
 it("blocks missing required fields and warns on optional fields",()=>{const required=field({source_column:"absent"});expect(validateFieldBindings([required],student,"School").some(i=>i.severity==="error")).toBe(true);const optional=field({required:false,source_column:"absent"});expect(validateFieldBindings([optional],student,"School").some(i=>i.code==="OPTIONAL_FIELD_EMPTY")).toBe(true);});
 it("rejects active or externally referenced SVG",()=>{expect(()=>sanitizeSvg('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>')).toThrow();expect(()=>sanitizeSvg('<svg><image href="https://evil.invalid/x.png"/></svg>')).toThrow();expect(sanitizeSvg('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100"/></svg>').toString()).toContain("<svg");});
 it("renders a raster template with Unicode text at exact requested dimensions",async()=>{const out=await render(await png(),[field()]);expect(out.mimeType).toBe("image/png");expect(out.widthPx).toBe(100);expect(out.heightPx).toBe(100);expect((await sharp(out.bytes).metadata()).width).toBe(100);});
 it("produces deterministic bytes for identical inputs",async()=>{const template=await png();const a=await render(template,[field()]),b=await render(template,[field()]);expect(a.inputHash).toBe(b.inputHash);expect(a.outputHash).toBe(b.outputHash);});
 it("changes the output fingerprint when mapped student data changes",async()=>{const template=await png(),a=await render(template,[field()]),other={...student,data:{...student.data,student_name:"सिया वर्मा"}},b=await renderIdCard({template,templateType:"image/png",templateId:"tpl-fixture",templateVersion:1,fields:[field()],student:other,schoolName:"Fictional School",photo:null,photoApproved:false,options});expect(a.inputHash).not.toBe(b.inputHash);expect(a.outputHash).not.toBe(b.outputHash);});
 it("requires an approved photo only when the mapped photo field is required",async()=>{const template=await png(),photoField=field({id:"photo",key:"student_photo",label:"Photo",field_type:"photo",source_column:null,required:true});await expect(render(template,[photoField])).rejects.toThrow(/photograph|photo/i);const optional=await render(template,[{...photoField,required:false}]);expect(optional.bytes.length).toBeGreaterThan(0);});
 it("places the approved photo in the configured box without changing its aspect ratio",async()=>{const template=await png(),photo=await png(20,30,{r:220,g:20,b:20,alpha:1}),photoField=field({id:"photo",key:"student_photo",label:"Photo",field_type:"photo",source_column:null,x:10,y:10,width:30,height:50,required:true,fit_mode:"contain"}),out=await renderIdCard({template,templateType:"image/png",templateId:"tpl-fixture",templateVersion:1,fields:[photoField],student,schoolName:"Fictional School",photo,photoApproved:true,options});expect(out.bytes.length).toBeGreaterThan(0);});
 it("renders configured QR and barcode fields as graphics instead of raw text",async()=>{const template=await png(),fields=[field({id:"qr",key:"student_qr",label:"QR",field_type:"qr",source_column:"admission_no",x:4,y:35,width:30,height:30,required:true}),field({id:"barcode",key:"student_barcode",label:"Barcode",field_type:"barcode",source_column:"admission_no",x:40,y:35,width:55,height:25,required:true,render_options:{barcodeType:"code128"}})],out=await render(template,fields);expect(out.bytes.length).toBeGreaterThan(200);expect(out.outputHash).not.toBe((await render(template,[field()])).outputHash);});
 it("renders major Indian scripts with script-specific shaping fonts",async()=>{const template=await png(),bengali={...student,data:{student_name:"রিয়া সেন"}},tamil={...student,data:{student_name:"அருண் குமார்"}},base={template,templateType:"image/png",templateId:"script-fixture",templateVersion:1,fields:[field()],schoolName:"Fictional School",photo:null,photoApproved:false,options};const a=await renderIdCard({...base,student:bengali}),b=await renderIdCard({...base,student:tamil});expect(a.outputHash).not.toBe(b.outputHash);});
 it("blocks a required field when the selected font has no glyphs",async()=>{const template=await png(),unsupported={...student,data:{student_name:"😀"}};await expect(renderIdCard({template,templateType:"image/png",templateId:"missing-glyph-fixture",templateVersion:1,fields:[field()],student:unsupported,schoolName:"Fictional School",photo:null,photoApproved:false,options})).rejects.toThrow(/glyph/i);});
 it("keeps vector PDF templates as PDF output",async()=>{const pdf=await PDFDocument.create();pdf.addPage([72,72]);const bytes=Buffer.from(await pdf.save());const out=await renderIdCard({template:bytes,templateType:"application/pdf",templateId:"pdf-fixture",templateVersion:1,fields:[field({x:5,y:5,width:60,height:20})],student,schoolName:"Fictional School",photo:null,photoApproved:false,options:{widthMm:25.4,heightMm:25.4,dpi:300,format:"pdf"}});expect(out.mimeType).toBe("application/pdf");expect(out.bytes.subarray(0,4).toString()).toBe("%PDF");});
});
