import {describe,expect,it} from "vitest";
import * as XLSX from "xlsx";
import {parseWorkbook,normalizeColumnName,validateStudentRows} from "@/lib/imports/student-spreadsheet";
function workbook(rows: unknown[][], name="students.xlsx") { const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),"Students");return {buffer:XLSX.write(wb,{type:"array",bookType:name.endsWith(".csv")?"csv":"xlsx"}),name};}
describe("student spreadsheet import",()=>{
 it("detects headers and serial column despite title rows",()=>{const x=workbook([["School list"],["Generated"],["Serial No","Name","Father Name","Class"],[1,"Asha","Ravi","5"],[2,"Imran","Salim","6"]]);const p=parseWorkbook(x.buffer,x.name);expect(p.headerRow).toBe(3);expect(p.serialColumn).toBe("Serial No");expect(p.summary.total).toBe(2);});
 it("preserves values and flags duplicate, missing serial and blank rows",()=>{const x=workbook([["S.No","Name","DOB"],[1,"Asha","2014-01-02"],[1,"Ravi",null],[null,"Missing serial",null],[null,null,null]]);const p=parseWorkbook(x.buffer,x.name);expect(p.summary.duplicates).toBe(2);expect(p.summary.missingSerial).toBe(1);expect(p.summary.blank).toBe(1);expect(p.rows[0].values.Name).toBe("Asha");});
 it("normalizes names deterministically",()=>{expect(normalizeColumnName("  Father_Name. ")).toBe("father name");});
 it("scales to 10,000 records without dropping rows",()=>{const rows:unknown[][]=[["Serial","Name","Class"]];for(let i=1;i<=10000;i++)rows.push([i,`Student ${i}`,String(i%12+1)]);const x=workbook(rows);const p=parseWorkbook(x.buffer,x.name);expect(p.summary.total).toBe(10000);expect(p.summary.invalid).toBe(0);});
 it("revalidates rows when the user changes serial column",()=>{const x=workbook([["Serial","ID","Name"],[null,7,"A"],[null,8,"B"]]);const p=parseWorkbook(x.buffer,x.name);const fixed=p.rows.map(r=>({...r,values:{...r.values,Serial:r.values.ID}}));expect(validateStudentRows(fixed,"Serial").every(r=>r.serialNumber)).toBe(true);});
 it("detects duplicate serials after canonicalizing leading zeros while preserving display values",()=>{const x=workbook([["Serial","Name"],["001","Asha"],["1","Ravi"]]);const p=parseWorkbook(x.buffer,x.name);expect(p.rows[0].serialNumber).toBe("001");expect(p.rows[0].issues).toContain("Duplicate serial number");expect(p.rows[1].issues).toContain("Duplicate serial number");expect(p.summary.duplicates).toBe(2);});
 it("rejects non-numeric serials and rechecks padded duplicates after column remapping",()=>{const x=workbook([["Serial","Alternate","Name"],["001","1","Asha"],["1","2","Ravi"],["ABC","3","Imran"]]);const p=parseWorkbook(x.buffer,x.name);const rows=validateStudentRows(p.rows.map(r=>({...r,values:{...r.values,Serial:r.values.Alternate}})),"Serial");expect(rows[0].serialNumber).toBe("1");expect(rows[0].issues).toContain("Duplicate serial number");expect(rows[1].issues).toContain("Duplicate serial number");const invalid=validateStudentRows(p.rows,"Serial").find(r=>r.serialNumber==="ABC");expect(invalid?.issues).toContain("Serial number must be a whole number");});

});
