import { createHash } from "node:crypto";
export type Severity="CRITICAL"|"ERROR"|"WARNING"|"INFO";
export type FindingStatus="OPEN"|"IN_REVIEW"|"RESOLVED"|"WAIVED";
export type Finding={ruleId:string;ruleVersion:number;severity:Severity;status:FindingStatus;message:string;correctiveAction:string;studentId?:string|null;generatedCardId?:string|null;batchId?:string|null;fieldRef?:string|null;assetRef?:string|null;inputFingerprint:string;details?:Record<string,unknown>};
type Student={id:string;project_id?:string;serial_number:number|null;data?:Record<string,unknown>|null};
type Field={id?:string;key?:string;label?:string;field_type?:string;source_column?:string|null;required?:boolean;visible?:boolean;x:number;y:number;width:number;height:number;font_family?:string|null;font_size?:number|null;color?:string|null;static_value?:string|null;render_options?:Record<string,unknown>|null};
const norm=(s:string)=>s.normalize("NFKC").trim().toLowerCase().replace(/[\s_-]+/g,"");
const empty=(v:unknown)=>v===undefined||v===null||String(v).trim()==="";
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
function make(ruleId:string,severity:Severity,message:string,correctiveAction:string,fingerprint:unknown,more:Partial<Finding>={}):Finding{return{ruleId,ruleVersion:1,severity,status:"OPEN",message,correctiveAction,inputFingerprint:hash(fingerprint),...more}}
export function validateStudents(students:Student[],requiredFields:string[]=[],options:{admissionNumberUnique?:boolean}={}):Finding[]{
 const out:Finding[]=[],serials=new Map<string,Student[]>(),admissions=new Map<string,Student[]>();
 for(const s of students){const d=s.data??{},serial=s.serial_number==null?"":String(s.serial_number).trim();
 if(!serial)out.push(make("STUDENT_SERIAL_MISSING","CRITICAL","Student serial number is missing.","Correct the serial number in the source sheet and verify the imported record.",{id:s.id,serial},{studentId:s.id}));
 else serials.set(serial,[...(serials.get(serial)??[]),s]);
 const nk=Object.keys(d).find(k=>["studentname","name","fullname","pupilname"].includes(norm(k)));
 const nameValue=nk?d[nk]:undefined;if(!nk||empty(nameValue))out.push(make("STUDENT_NAME_MISSING","ERROR","Required student name is missing.","Map the correct name column and verify this student record.",{id:s.id,key:nk,value:nameValue},{studentId:s.id,fieldRef:nk??"student_name"}));
 for(const req of requiredFields){const k=Object.keys(d).find(x=>norm(x)===norm(req));const value=k?d[k]:undefined;if(!k||empty(value))out.push(make("STUDENT_REQUIRED_FIELD_MISSING","ERROR","A project-required student field is missing.","Fill the required field or update the school-specific configuration.",{id:s.id,req,k,value},{studentId:s.id,fieldRef:req}))}
 for(const [k,v]of Object.entries(d)){if(typeof v!=="string")continue;
 if(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(v))out.push(make("STUDENT_CONTROL_CHARACTER","WARNING","A field contains control characters.","Review the original spreadsheet cell; no value was changed automatically.",{id:s.id,k,v},{studentId:s.id,fieldRef:k}));
 if(/^\s*[=+@]/.test(v))out.push(make("STUDENT_FORMULA_LIKE_VALUE","WARNING","A value resembles a spreadsheet formula or untrusted expression.","Confirm the literal value is intentional before export.",{id:s.id,k,v},{studentId:s.id,fieldRef:k}));
 if(v!==v.trim())out.push(make("STUDENT_WHITESPACE","INFO","A field contains leading or trailing whitespace.","Review the source value; preserve it unless an authorized correction is made.",{id:s.id,k,v},{studentId:s.id,fieldRef:k}));
 if(/(?:dob|birth|date|expiry|joining)/i.test(k)&&v.trim()&&!/^\d{4}-\d{2}-\d{2}$/.test(v.trim())&&!/^\d{1,2}[/-]\d{1,2}[/-]\d{2,4}$/.test(v.trim())&&Number.isNaN(Date.parse(v.trim())))out.push(make("STUDENT_DATE_FORMAT_REVIEW","WARNING","A date-like field uses an unrecognized date format.","Confirm the date format and correct it only through the authorized student-data editor.",{id:s.id,k,v},{studentId:s.id,fieldRef:k}));if(v.length>300)out.push(make("STUDENT_FIELD_TOO_LONG","WARNING","A field exceeds the default 300-character review threshold.","Review the value and configured text-box capacity.",{id:s.id,k,length:v.length},{studentId:s.id,fieldRef:k}));
 }
 const ak=Object.keys(d).find(k=>["admissionnumber","admissionno","admissionid","enrollmentnumber","enrollmentno"].includes(norm(k)));
 if(ak&&!empty(d[ak])){const a=String(d[ak]).normalize("NFKC").trim().toLocaleLowerCase("en-IN");admissions.set(a,[...(admissions.get(a)??[]),s])}
 }
 for(const [serial,rows]of serials)if(rows.length>1)for(const s of rows)out.push(make("STUDENT_SERIAL_DUPLICATE","CRITICAL","More than one student record uses the same serial number.","Resolve duplicate serial numbers before matching photos or generating cards.",{serial,ids:rows.map(r=>r.id).sort()},{studentId:s.id,fieldRef:"serial_number"}));
 for(const [admission,rows]of admissions)if(options.admissionNumberUnique!==false&&rows.length>1)for(const s of rows)out.push(make("STUDENT_ADMISSION_DUPLICATE","ERROR","Admission number is duplicated within this project.","Confirm the school's uniqueness policy and correct the source record if needed.",{admission,ids:rows.map(r=>r.id).sort()},{studentId:s.id,fieldRef:"admission_number"}));
 return out;
}
export function validateTemplateConfiguration(template:any,fields:Field[],fingerprint:unknown=null):Finding[]{
 const out:Finding[]=[],w=Number(template?.width_px),h=Number(template?.height_px),base={id:template?.id,version:template?.version_number,config:template?.render_config};
 if(!template?.source_path)out.push(make("TEMPLATE_SOURCE_MISSING","CRITICAL","Template source file is missing.","Upload or restore the original template file.",base,{assetRef:String(template?.id??"template")}));
 if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1)out.push(make("TEMPLATE_DIMENSIONS_INVALID","CRITICAL","Template dimensions are missing or invalid.","Confirm the template's actual pixel dimensions and re-analyze it.",base,{assetRef:String(template?.id??"template")}));
 if(!Number.isInteger(Number(template?.version_number))||Number(template?.version_number)<1)out.push(make("TEMPLATE_VERSION_INVALID","CRITICAL","Template version is invalid.","Save a valid template version before production.",base,{assetRef:String(template?.id??"template")}));
 if(!fields?.length)out.push(make("TEMPLATE_FIELDS_MISSING","CRITICAL","No mapped fields are configured.","Map required student fields and a photo box before production.",base,{assetRef:String(template?.id??"template")}));
 for(const f of fields??[]){if(f.visible===false||f.render_options?.visible===false)continue;const x=Number(f.x),y=Number(f.y),fw=Number(f.width),fh=Number(f.height),label=String(f.label??f.key??f.id??"field"),photo=["photo","image","student_photo","student-photo"].includes(String(f.field_type??"").toLowerCase());
 if(![x,y,fw,fh].every(Number.isFinite)||x<0||y<0||fw<=0||fh<=0||(w>0&&x+fw>w)||(h>0&&y+fh>h))out.push(make("TEMPLATE_FIELD_OUT_OF_BOUNDS","CRITICAL","A mapped field is outside template boundaries.","Adjust this field's coordinates and dimensions in the template editor.",{base,field:f},{fieldRef:String(f.id??label),assetRef:String(template?.id??"template")}));
 if(f.required&&!photo&&String(f.source_column??"").trim()===""&&typeof f.render_options?.staticValue!=="string"&&empty(f.static_value)&&!["school_name","serial_number"].includes(String(f.key??"")))out.push(make("TEMPLATE_REQUIRED_MAPPING_MISSING","CRITICAL","A required field has no source mapping.","Map this field to a student column or explicit static value.",{base,field:f},{fieldRef:String(f.id??label),assetRef:String(template?.id??"template")}));
 if(f.color&&!/^#[0-9a-f]{3}(?:[0-9a-f]{3})?$/i.test(f.color))out.push(make("TEMPLATE_COLOR_INVALID","WARNING","A field color is not a supported hexadecimal color.","Choose a valid #RGB or #RRGGBB color.",{base,field:f},{fieldRef:String(f.id??label)}));
 if(f.font_size!=null&&(!Number.isFinite(Number(f.font_size))||Number(f.font_size)<1||Number(f.font_size)>300))out.push(make("TEMPLATE_FONT_SIZE_INVALID","ERROR","A field font size is outside supported bounds.","Choose a font size from 1 to 300 template units.",{base,field:f},{fieldRef:String(f.id??label)}));
 }
 for(let i=0;i<(fields??[]).length;i++)for(let j=i+1;j<(fields??[]).length;j++){const a=fields[i],b=fields[j];if(a.visible===false||b.visible===false||a.render_options?.visible===false||b.render_options?.visible===false)continue;const overlap=Number(a.x)<Number(b.x)+Number(b.width)&&Number(a.x)+Number(a.width)>Number(b.x)&&Number(a.y)<Number(b.y)+Number(b.height)&&Number(a.y)+Number(a.height)>Number(b.y);if(overlap&&a.render_options?.allowOverlap!==true&&b.render_options?.allowOverlap!==true)out.push(make("TEMPLATE_FIELDS_OVERLAP","WARNING","Two visible mapped fields overlap and may obscure content.","Inspect both fields; explicitly set render_options.allowOverlap=true for intentional overlap.",{template:template?.id,version:template?.version_number,a:a.id,b:b.id},{fieldRef:String(a.id??a.key??"")}))}
 return out.map(f=>({...f,inputFingerprint:hash({fingerprint,ruleFingerprint:f.inputFingerprint})}));
}
export function validatePhotoAssignments(students:Student[],photos:any[],projectId:string,requiresPhoto=true,thresholds:{minWidthPx?:number;minHeightPx?:number}={}):Finding[]{
 const out:Finding[]=[],byStudent=new Map<string,any[]>();
 for(const p of photos){if(p.project_id!==projectId)out.push(make("PHOTO_CROSS_PROJECT","CRITICAL","A photo reference belongs to another project.","Remove the cross-project reference and assign a photo from this project.",{id:p.id,projectId:p.project_id},{studentId:p.student_id??null,assetRef:String(p.id)}));
 if(p.student_id)byStudent.set(p.student_id,[...(byStudent.get(p.student_id)??[]),p]);
 if(!p.student_id||!students.some(s=>s.id===p.student_id))out.push(make("PHOTO_UNMATCHED","WARNING","A photo is not matched to a student in this project.","Match it using a persisted student ID and review ambiguous serial numbers.",{id:p.id,studentId:p.student_id,projectId:p.project_id},{assetRef:String(p.id)}));
 if(p.student_id&&(!p.processed_storage_path||p.processing_status!=="APPROVED"||p.match_status!=="APPROVED"||!p.crop_approved_at))out.push(make("PHOTO_NOT_APPROVED",requiresPhoto?"ERROR":"WARNING","The assigned photo or crop has not completed approval.","Review the match and crop, then approve the processed derivative.",{id:p.id,version:p.image_version,processed:p.processed_storage_path,processing:p.processing_status,match:p.match_status,crop:!!p.crop_approved_at},{studentId:p.student_id,assetRef:String(p.id)}));if(Number(p.face_count)>1)out.push(make("PHOTO_MULTIPLE_FACES","WARNING","More than one face was detected in the source photo.","Confirm the intended student is the only person shown in the approved crop; automated face detection does not identify the person.",{id:p.id,faceCount:p.face_count,version:p.image_version},{studentId:p.student_id??null,assetRef:String(p.id)}));if(Number(p.face_count)===0)out.push(make("PHOTO_NO_FACE_DETECTED","WARNING","No face was detected by the available photo-quality check.","Manually inspect the image and crop; a face-detection result is not an identity proof.",{id:p.id,faceCount:p.face_count,version:p.image_version},{studentId:p.student_id??null,assetRef:String(p.id)}));for(const code of Array.isArray(p.processing_warnings)?p.processing_warnings:[])out.push(make("PHOTO_QUALITY_REVIEW","WARNING","Photo processing flagged a quality concern ("+String(code)+").","Review the approved crop and print-size clarity before approval.",{id:p.id,code,version:p.image_version},{studentId:p.student_id??null,assetRef:String(p.id)}));if((Number(p.width_px)>0&&Number(p.width_px)<(thresholds.minWidthPx??600))||(Number(p.height_px)>0&&Number(p.height_px)<(thresholds.minHeightPx??800)))out.push(make("PHOTO_LOW_RESOLUTION","WARNING","Photo source resolution is below the default 600×800 review threshold.","Inspect print sharpness at final size; adjust school-specific thresholds where appropriate.",{id:p.id,width:p.width_px,height:p.height_px,version:p.image_version},{studentId:p.student_id??null,assetRef:String(p.id)}))}
 for(const s of students){const approved=(byStudent.get(s.id)??[]).filter(p=>p.project_id===projectId&&p.match_status==="APPROVED"&&p.processing_status==="APPROVED"&&p.crop_approved_at&&p.processed_storage_path);
 if(requiresPhoto&&!approved.length)out.push(make("PHOTO_REQUIRED_MISSING","CRITICAL","No approved processed photo is linked to this student.","Match the correct photo, approve its crop, and verify the assignment before generating a card.",{student:s.id,photos:(byStudent.get(s.id)??[]).map(p=>({id:p.id,status:p.match_status,version:p.image_version}))},{studentId:s.id}));
 if(approved.length>1)out.push(make("PHOTO_MULTIPLE_APPROVED","CRITICAL","More than one approved photo is assigned to this student.","Choose one approved photo and revoke or unassign the others.",{student:s.id,photos:approved.map(p=>({id:p.id,version:p.image_version}))},{studentId:s.id}))}
 return out;
}
export function validateRenderedCard(card:any,template:any,options:{storedHash?:string|null;storedBytesReadable?:boolean;actualWidth?:number|null;actualHeight?:number|null;expectedWidth?:number|null;expectedHeight?:number|null;currentPhotoId?:string|null;currentPhotoVersion?:number|null;usesPhoto?:boolean;currentStudentUpdatedAt?:string|null;renderedAt?:string|null}={}):Finding[]{
 const out:Finding[]=[],base={id:card?.id,student:card?.student_id,template:card?.template_id,templateVersion:card?.template_version,input:card?.render_input_hash,output:card?.output_sha256};
 if(card?.status!=="generated"||!card?.storage_path)out.push(make("CARD_OUTPUT_MISSING","CRITICAL","Generated card output is missing or not successful.","Regenerate the card and verify its private storage object.",base,{studentId:card?.student_id,generatedCardId:card?.id}));
 if(!card?.output_sha256)out.push(make("CARD_OUTPUT_HASH_MISSING","CRITICAL","Stored output hash is missing.","Regenerate the card so the output can be verified before approval or export.",base,{studentId:card?.student_id,generatedCardId:card?.id}));if(options.storedBytesReadable===false)out.push(make("CARD_OUTPUT_UNREADABLE","CRITICAL","Stored output could not be decoded or read.","Regenerate the card and verify storage permissions and encoding.",base,{studentId:card?.student_id,generatedCardId:card?.id}));
 if(options.storedHash&&card?.output_sha256&&options.storedHash!==card.output_sha256)out.push(make("CARD_OUTPUT_HASH_MISMATCH","CRITICAL","Stored object hash does not match recorded render output.","Do not export this artifact; regenerate it.",base,{studentId:card?.student_id,generatedCardId:card?.id}));
 if(template&&(card?.template_id!==template.id||Number(card?.template_version)!==Number(template.version_number)))out.push(make("CARD_TEMPLATE_STALE","ERROR","Rendered card references an outdated template version.","Revalidate and regenerate against the current intended template.",base,{studentId:card?.student_id,generatedCardId:card?.id}));
 if(options.usesPhoto&&((options.currentPhotoId??null)!==(card?.photo_id??null)||(options.currentPhotoVersion??null)!==(card?.photo_version??null)))out.push(make("CARD_PHOTO_STALE","ERROR","The approved photo changed after this card was rendered.","Regenerate the card using the current approved photo derivative.",{base,currentPhotoId:options.currentPhotoId,currentPhotoVersion:options.currentPhotoVersion},{studentId:card?.student_id,generatedCardId:card?.id}));if(options.currentStudentUpdatedAt&&options.renderedAt&&Date.parse(options.currentStudentUpdatedAt)>Date.parse(options.renderedAt))out.push(make("CARD_STUDENT_DATA_STALE","ERROR","Student data changed after this card was rendered.","Regenerate the card from the latest saved student record.",{base,studentUpdatedAt:options.currentStudentUpdatedAt,renderedAt:options.renderedAt},{studentId:card?.student_id,generatedCardId:card?.id}));
 if(options.actualWidth&&options.expectedWidth&&options.actualHeight&&options.expectedHeight&&(options.actualWidth!==options.expectedWidth||options.actualHeight!==options.expectedHeight))out.push(make("CARD_DIMENSIONS_MISMATCH","CRITICAL","Output dimensions do not match configured print dimensions.","Regenerate using the intended physical dimensions and DPI.",{base,actualWidth:options.actualWidth,actualHeight:options.actualHeight,expectedWidth:options.expectedWidth,expectedHeight:options.expectedHeight},{studentId:card?.student_id,generatedCardId:card?.id}));
 for(const e of (Array.isArray(card?.render_errors)?card.render_errors:Array.isArray(card?.validation_errors)?card.validation_errors:[]))out.push(make(String(e.code??"CARD_RENDER_ERROR"),"ERROR",String(e.message??"Rendering reported an error."),"Correct the field or template issue and regenerate.",{base,e},{studentId:card?.student_id,generatedCardId:card?.id,fieldRef:e.fieldId??null}));
 for(const w of (Array.isArray(card?.render_warnings)?card.render_warnings:Array.isArray(card?.validation_warnings)?card.validation_warnings:[]))out.push(make(String(w.code??"CARD_RENDER_WARNING"),"WARNING",String(w.message??"Rendering reported a warning."),"Inspect the rendered card at readable zoom and resolve the warning before approval.",{base,w},{studentId:card?.student_id,generatedCardId:card?.id,fieldRef:w.fieldId??null}));
 return out;
}
export function isCardExportEligible(input:{approvalStatus?:string|null;findings:Finding[];allowWarnings?:boolean}):{eligible:boolean;reasons:string[]}{const reasons:string[]=[];if(input.approvalStatus!=="approved")reasons.push("Human approval is required.");for(const f of input.findings)if(f.severity==="CRITICAL"&&f.status!=="RESOLVED")reasons.push("Critical finding cannot be waived or bypassed: "+f.message);else if(f.status!=="RESOLVED"&&f.status!=="WAIVED"&&(f.severity==="ERROR"||(!input.allowWarnings&&f.severity==="WARNING")))reasons.push(f.message);return{eligible:reasons.length===0,reasons}}
export function mayResolveFinding(f:Pick<Finding,"severity">,action:"resolve"|"waive",actorRole:"owner"|"reviewer"|"member",hasCorrectionNote:boolean):{allowed:boolean;reason?:string}{if(action==="waive"&&f.severity==="CRITICAL")return{allowed:false,reason:"Critical findings cannot be waived."};if(action==="waive"&&actorRole!=="owner")return{allowed:false,reason:"Only the project owner may waive non-critical findings."};if(action==="resolve"&&f.severity==="CRITICAL")return{allowed:false,reason:"Critical findings close only after revalidation confirms the issue is gone."};if(!hasCorrectionNote)return{allowed:false,reason:"A corrective-action note is required."};return{allowed:true}}
export function findingKey(projectId:string,f:Finding):string{return createHash("sha256").update([projectId,f.studentId??"",f.generatedCardId??"",f.batchId??"",f.ruleId,f.inputFingerprint].join("|")).digest("hex")}
