"use server";
import { createClient } from "@/lib/supabase/server";
import { STORAGE_BUCKETS, type StorageBucket, projectObjectPath } from "@/lib/supabase/storage";
const LIMITS:Record<StorageBucket,number>={[STORAGE_BUCKETS.templates]:20*1024*1024,[STORAGE_BUCKETS.studentPhotos]:10*1024*1024,[STORAGE_BUCKETS.generatedCards]:20*1024*1024,[STORAGE_BUCKETS.exports]:100*1024*1024};
const TYPES:Record<StorageBucket,string[]>={[STORAGE_BUCKETS.templates]:["image/png","image/jpeg"],[STORAGE_BUCKETS.studentPhotos]:["image/jpeg","image/png","image/webp"],[STORAGE_BUCKETS.generatedCards]:["image/png","image/jpeg","application/pdf"],[STORAGE_BUCKETS.exports]:["application/zip","application/pdf"]};
function pngDimensions(b:Uint8Array){if(b.length<24||b[0]!==137||b[1]!==80||b[2]!==78||b[3]!==71)return null;const d=new DataView(b.buffer,b.byteOffset,b.byteLength);const w=d.getUint32(16),h=d.getUint32(20);return w&&h?{width:w,height:h}:null}
function jpegDimensions(b:Uint8Array){if(b.length<4||b[0]!==255||b[1]!==216)return null;let i=2;while(i+9<b.length){if(b[i]!==255){i++;continue}const m=b[i+1];i+=2;if(m===216||m===217)continue;if(i+2>b.length)return null;const n=(b[i]<<8)|b[i+1];if(n<2||i+n>b.length)return null;const sof=[192,193,194,195,197,198,199,201,202,203,205,206,207].includes(m);if(sof)return{width:(b[i+5]<<8)|b[i+6],height:(b[i+3]<<8)|b[i+4]};i+=n}return null}
async function validateTemplate(f:File){if(!f.size||f.size>20*1024*1024)throw new Error("Template must be between 1 byte and 20 MB.");if(!["image/png","image/jpeg"].includes(f.type))throw new Error("Only PNG, JPG, and JPEG templates are supported.");const b=new Uint8Array(await f.arrayBuffer());const d=f.type==="image/png"?pngDimensions(b):jpegDimensions(b);if(!d)throw new Error("The image is corrupted or could not be decoded.");if(d.width<300||d.height<300)throw new Error("Template resolution is too small. Use at least 300×300 pixels.");if(d.width>12000||d.height>12000)throw new Error("Template dimensions are too large. Maximum is 12000×12000 pixels.");return d}
async function auth(){const s=await createClient();const{data:claims}=await s.auth.getClaims();const uid=claims?.claims?.sub;if(!uid)throw new Error("Unauthorized");return{s,uid}}
export async function createProject(input:{name:string;schoolName:string;schoolAddress?:string;academicSession?:string}){const{s,uid}=await auth();const name=input.name.trim(),schoolName=input.schoolName.trim();if(!name||!schoolName)throw new Error("Project name and school name are required");const{data,error}=await s.from("school_projects").insert({owner_id:uid,name,school_name:schoolName,school_address:input.schoolAddress?.trim()||null,academic_session:input.academicSession?.trim()||null,status:"draft"}).select("id,name,school_name,status").single();if(error)throw new Error(error.message);return data}
export async function updateProject(input:{projectId:string;name:string;schoolName:string;schoolAddress?:string;academicSession?:string}){const{s}=await auth();const name=input.name.trim(),schoolName=input.schoolName.trim();if(!name||!schoolName)throw new Error("Project name and school name are required");const{data,error}=await s.from("school_projects").update({name,school_name:schoolName,school_address:input.schoolAddress?.trim()||null,academic_session:input.academicSession?.trim()||null,updated_at:new Date().toISOString()}).eq("id",input.projectId).select("id,name,school_name,school_address,academic_session,status").single();if(error)throw new Error(error.message);return data}
export async function uploadTemplate(input:{projectId:string;file:File}){const{s,uid}=await auth();const dimensions=await validateTemplate(input.file);const{data:project}=await s.from("school_projects").select("id").eq("id",input.projectId).maybeSingle();if(!project)throw new Error("Project not found.");const{data:current}=await s.from("templates").select("id,version_number").eq("project_id",input.projectId).order("version_number",{ascending:false}).limit(1);const next=(current?.[0]?.version_number??0)+1;const path=projectObjectPath(uid,input.projectId,input.file.name);const{error:up}=await s.storage.from(STORAGE_BUCKETS.templates).upload(path,input.file,{contentType:input.file.type,upsert:false});if(up)throw new Error(up.message);if(current?.[0]){const{error:e}=await s.from("templates").update({is_active:false,updated_at:new Date().toISOString()}).eq("project_id",input.projectId).eq("is_active",true);if(e){await s.storage.from(STORAGE_BUCKETS.templates).remove([path]);throw new Error(e.message)}}const{data:t,error}=await s.from("templates").insert({owner_id:uid,project_id:input.projectId,name:input.file.name,source_path:path,source_type:input.file.type,width_px:dimensions.width,height_px:dimensions.height,analysis_status:"pending",analysis:{engine:"manual-first",version:1,source:"uploaded"},version_number:next,is_active:true}).select("id,name,source_path,source_type,width_px,height_px,analysis_status,version_number,is_active,created_at").single();if(error){await s.storage.from(STORAGE_BUCKETS.templates).remove([path]);throw new Error(error.message)}return t}
export async function deleteTemplate(input:{projectId:string;templateId:string}){const{s}=await auth();const{data:t}=await s.from("templates").select("id,source_path,is_active").eq("id",input.templateId).eq("project_id",input.projectId).maybeSingle();if(!t)throw new Error("Template not found.");const{error}=await s.from("templates").delete().eq("id",input.templateId).eq("project_id",input.projectId);if(error)throw new Error(error.message);if(t.source_path)await s.storage.from(STORAGE_BUCKETS.templates).remove([t.source_path]);return{deleted:true,wasActive:t.is_active}}
export async function createTemplatePreview(input:{bucket:StorageBucket;path:string}){const{s}=await auth();if(input.bucket!==STORAGE_BUCKETS.templates)throw new Error("Invalid template bucket.");const{data,error}=await s.storage.from(input.bucket).createSignedUrl(input.path,600);if(error)throw new Error(error.message);return data.signedUrl}
export async function uploadProjectFile(input:{projectId:string;bucket:StorageBucket;file:File}){const{s,uid}=await auth();if(!Object.values(STORAGE_BUCKETS).includes(input.bucket))throw new Error("Invalid storage bucket");if(!input.file.size||input.file.size>LIMITS[input.bucket])throw new Error("File exceeds the allowed size");if(!TYPES[input.bucket].includes(input.file.type))throw new Error("File type is not allowed");const{data:project,error:pe}=await s.from("school_projects").select("id").eq("id",input.projectId).maybeSingle();if(pe)throw new Error(pe.message);if(!project)throw new Error("Project not found");const path=projectObjectPath(uid,input.projectId,input.file.name);const{error}=await s.storage.from(input.bucket).upload(path,input.file,{contentType:input.file.type,upsert:false});if(error)throw new Error(error.message);return{bucket:input.bucket,path}}
export async function createProjectDownload(input:{bucket:StorageBucket;path:string;expiresIn?:number}){const{s}=await auth();if(!Object.values(STORAGE_BUCKETS).includes(input.bucket))throw new Error("Invalid storage bucket");const{data,error}=await s.storage.from(input.bucket).createSignedUrl(input.path,Math.min(Math.max(input.expiresIn??300,30),3600));if(error)throw new Error(error.message);return data.signedUrl}
export async function saveTemplateFields(input:{projectId:string;templateId:string;fields:Array<{id?:string;key:string;label:string;field_type:string;required:boolean;x:number;y:number;width:number;height:number;font_family:string|null;font_size:number|null;font_weight:string|null;color:string|null;alignment:string|null;fit_mode:string|null;source_column:string|null;confidence:number|null}>}){const{s,uid}=await auth();const{data:t}=await s.from("templates").select("id").eq("id",input.templateId).eq("project_id",input.projectId).maybeSingle();if(!t)throw new Error("Template not found.");const fields=input.fields.slice(0,100).map((f,i)=>({...f,id:undefined,template_id:input.templateId,owner_id:uid,sort_order:i,x:Math.max(0,f.x),y:Math.max(0,f.y),width:Math.max(1,f.width),height:Math.max(1,f.height),confidence:f.confidence==null?1:Math.min(1,Math.max(0,f.confidence))}));const{error:de}=await s.from("template_fields").delete().eq("template_id",input.templateId);if(de)throw new Error(de.message);if(fields.length){const{error:ie}=await s.from("template_fields").insert(fields);if(ie)throw new Error(ie.message)}return{saved:fields.length}}