"use client";
import { useState } from "react";
type StudentOption={id:string;serial_number:number;label:string};
type Props={projectId:string;templateId:string;templateName:string;templateVersion:number;templateType:string;templateWidth:number;templateHeight:number;renderConfig?:Record<string,unknown>|null;students:StudentOption[]};
type Preflight={totalStudents:number;eligible:number;blocked:number;warningCount:number;configIssues?:string[];output?:{widthMm:number;heightMm:number;dpi:number;format:string};issues:Array<{serialNumber:number;eligible:boolean;issues:Array<{code:string;message:string;severity:string}>}>};
export function CardRenderingWorkspace({projectId,templateId,templateName,templateVersion,templateType,templateWidth,templateHeight,renderConfig,students}:Props){
 const c=renderConfig??{}, [widthMm,setWidthMm]=useState(String(c.widthMm??"")),[heightMm,setHeightMm]=useState(String(c.heightMm??"")),[dpi,setDpi]=useState(String(c.dpi??300)),[format,setFormat]=useState(String(c.format??"png")),[studentId,setStudentId]=useState(students[0]?.id??""),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[preflight,setPreflight]=useState<Preflight|null>(null),[result,setResult]=useState<any>(null);
 async function call(action:string){setBusy(action);setError("");setNotice("");try{const response=await fetch("/api/projects/"+projectId+"/render",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,studentId,widthMm:Number(widthMm),heightMm:Number(heightMm),dpi:Number(dpi),format,side:"front"})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Rendering request failed.");if(action==="preflight"){setPreflight(data);setNotice("Preflight completed. Review blocked students and warnings before production.");}else if(action==="save-config"){setNotice("Print settings saved to this template version.");}else{setResult(data);setNotice(data.reused?"Matching card output reused.":"Sample card rendered and saved successfully.");}}catch(e){setError(e instanceof Error?e.message:"Rendering request failed.");}finally{setBusy("");}}
 const canRender=!!studentId&&Number(widthMm)>0&&Number(heightMm)>0&&Number(dpi)>=72&&Number(dpi)<=1200;
 return <section className="pf-panel mt-5 p-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-300">Phase 8 · Rendering engine</p><h2 className="mt-1 text-xl font-bold">ID card rendering & print setup</h2><p className="pf-muted mt-1 text-sm">Template v{templateVersion} · {templateName} · {templateType} · source {templateWidth} × {templateHeight}</p></div><span className="rounded-full border border-white/15 px-3 py-1 text-xs">Deterministic output</span></div>
  <p className="pf-muted mt-3 text-sm">Coordinates are based on the uploaded template and scaled consistently for preview and output. Physical size is intentionally not guessed from pixels.</p>
  <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
   <label className="text-sm">Width (mm)<input type="number" min="1" max="500" step="0.1" value={widthMm} onChange={e=>setWidthMm(e.target.value)} placeholder="Confirm width" className="mt-1 w-full rounded-lg border border-white/15 bg-black/20 px-3 py-2"/></label>
   <label className="text-sm">Height (mm)<input type="number" min="1" max="500" step="0.1" value={heightMm} onChange={e=>setHeightMm(e.target.value)} placeholder="Confirm height" className="mt-1 w-full rounded-lg border border-white/15 bg-black/20 px-3 py-2"/></label>
   <label className="text-sm">Print resolution (DPI)<select value={dpi} onChange={e=>setDpi(e.target.value)} className="mt-1 w-full rounded-lg border border-white/15 bg-black/20 px-3 py-2">{[150,200,300,600,1200].map(n=><option key={n} value={n}>{n} DPI</option>)}</select></label>
   <label className="text-sm">Output format<select value={format} onChange={e=>setFormat(e.target.value)} className="mt-1 w-full rounded-lg border border-white/15 bg-black/20 px-3 py-2"><option value="png">PNG · lossless</option><option value="jpeg">JPEG · high quality</option><option value="pdf">PDF · print page</option></select></label>
  </div>
  <div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={!!busy} onClick={()=>void call("save-config")} className="rounded-lg border border-white/15 px-4 py-2 text-sm disabled:opacity-50">Save print settings</button><button type="button" disabled={!!busy} onClick={()=>void call("preflight")} className="rounded-lg border border-white/15 px-4 py-2 text-sm disabled:opacity-50">{busy==="preflight"?"Checking students…":"Run student preflight"}</button></div>
  <div className="mt-5 rounded-xl border border-white/10 p-4"><h3 className="font-semibold">Sample card</h3>{students.length?<><label className="mt-3 block text-sm">Sample student<select value={studentId} onChange={e=>setStudentId(e.target.value)} className="mt-1 w-full rounded-lg border border-white/15 bg-black/20 px-3 py-2">{students.map(s=><option key={s.id} value={s.id}>Serial {s.serial_number} · {s.label}</option>)}</select></label><button type="button" disabled={!!busy||!canRender} onClick={()=>void call("sample")} className="mt-3 rounded-lg bg-blue-500 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy==="sample"?"Rendering sample…":"Render sample card"}</button></>:<p className="pf-muted mt-2 text-sm">Import student records to enable sample rendering.</p>}
   {result?.previewUrl&&<div className="mt-4"><p className="text-sm font-medium">Actual renderer output · {result.widthPx} × {result.heightPx} px · {result.dpi} DPI</p>{result.format==="pdf"?<a className="mt-2 inline-block text-sm text-blue-300 underline" href={result.previewUrl} target="_blank" rel="noreferrer">Open print PDF</a>:<img src={result.previewUrl} alt="Rendered sample student ID card" className="mt-3 max-h-[520px] max-w-full rounded-lg border border-white/15 bg-white object-contain"/>}{result.warnings?.length>0&&<ul className="mt-3 list-disc pl-5 text-sm text-amber-300">{result.warnings.map((w:any,i:number)=><li key={w.code+"-"+i}>{w.message}</li>)}</ul>}</div>}
  </div>
  {preflight&&<div className="mt-4 rounded-xl border border-white/10 p-4"><h3 className="font-semibold">Preflight report</h3>{preflight.configIssues?.length? <ul className="mt-3 list-disc rounded-lg border border-red-400/30 p-3 pl-7 text-sm text-red-300">{preflight.configIssues.map((issue,i)=><li key={i}>{issue}</li>)}</ul>:null}<div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="pf-muted text-xs">Students</p><p className="text-2xl font-bold">{preflight.totalStudents}</p></div><div><p className="pf-muted text-xs">Eligible</p><p className="text-2xl font-bold">{preflight.eligible}</p></div><div><p className="pf-muted text-xs">Blocked</p><p className="text-2xl font-bold">{preflight.blocked}</p></div><div><p className="pf-muted text-xs">Warnings</p><p className="text-2xl font-bold">{preflight.warningCount}</p></div></div>{preflight.issues.length>0&&<div className="mt-3 max-h-52 overflow-auto text-sm">{preflight.issues.map((row,i)=><div key={row.serialNumber+"-"+i} className="border-t border-white/10 py-2"><p className="font-medium">Serial {row.serialNumber} · {row.eligible?"Warnings":"Blocked"}</p><ul className="list-disc pl-5">{row.issues.map((issue,j)=><li key={issue.code+"-"+j}>{issue.message}</li>)}</ul></div>)}</div>}</div>}
  {error&&<p role="alert" className="mt-3 rounded-lg border border-red-400/30 p-3 text-sm text-red-300">{error}</p>}{notice&&<p role="status" className="mt-3 rounded-lg border border-emerald-400/20 p-3 text-sm text-emerald-200">{notice}</p>}
  <p className="pf-muted mt-4 text-xs">This phase renders one student card at a time and provides a preflight report. Large batch orchestration and ZIP/print-sheet export remain Phase 9+ work.</p>
 </section>
}
