"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {Unzip,UnzipInflate,UnzipPassThrough} from "fflate";
import {createClient} from "@/lib/supabase/client";
import { CameraCapture } from "@/components/projects/camera-capture";
import {isSafeZipEntryName} from "@/lib/photos/matching";
import {approveStudentPhoto,assignStudentPhoto,createPhotoBatch,createPhotoUploadTicket,finishPhotoBatch,loadPhotoWorkspace,processPhotoMatches,recordPhotoUploadFailure,registerStudentPhoto,setPhotoSerialPrefix} from "@/app/dashboard/actions";

const MAX_FILES=500,MAX_FILE_BYTES=10*1024*1024,MAX_BATCH_BYTES=500*1024*1024,MAX_ZIP_BYTES=100*1024*1024,CONCURRENCY=4;
type Student={id:string;serial_number:number;data:Record<string,unknown>};
type Photo={id:string;student_id:string|null;serial_number:number|null;original_filename:string;original_serial_number:string|null;normalized_serial_number:string|null;storage_path:string;mime_type:string;width_px:number|null;height_px:number|null;file_size_bytes:number|null;content_sha256:string|null;matching_method:string|null;match_status:string;validation_errors:unknown;duplicate_of_id:string|null;batch_id:string|null;approved_at:string|null;created_at:string;previewUrl:string|null};
type Workspace={students:Student[];photos:Photo[];batches:Array<{id:string;name:string;status:string;total_count:number;completed_count:number;failed_count:number;review_count:number;created_at:string;completed_at:string|null}>;summary:{totalStudents:number;approvedPhotos:number;missingPhotos:number;unmatched:number;needsReview:number;duplicates:number;serialConflicts:number;failed:number}};
type QueueItem={id:string;file:File;status:"queued"|"uploading"|"uploaded"|"failed"|"cancelled";message?:string};
function studentLabel(s:Student){const entries=Object.entries(s.data??{});const name=entries.find(([k,v])=>/^(student\s*)?name$|student.?name/i.test(k)&&typeof v==="string"&&v.trim());const first=entries.find(([k,v])=>/name/i.test(k)&&!/father|mother|guardian/i.test(k)&&typeof v==="string"&&v.trim());return String(name?.[1]??first?.[1]??"Student")+" · #"+s.serial_number;}
function imageMime(file:File){if(file.type==="image/jpeg"||file.type==="image/png"||file.type==="image/webp")return file.type;const ext=file.name.toLowerCase().split(".").pop();return ext==="jpg"||ext==="jpeg"?"image/jpeg":ext==="png"?"image/png":ext==="webp"?"image/webp":"";}
async function extractZip(zip:File):Promise<File[]>{
 if(zip.size<1||zip.size>MAX_ZIP_BYTES)throw new Error("ZIP must be smaller than 100 MB.");
 const bytes=new Uint8Array(await zip.arrayBuffer());let total=0,count=0,aborted=false;const promises:Promise<File>[]=[];let rejectAll:(e:Error)=>void=()=>{};
 const failed=new Promise<never>((_,reject)=>{rejectAll=reject;});
 const unzip=new Unzip(entry=>{
  if(aborted)return;
  const name=entry.name.replace(/\\/g,"/");
  if(name.endsWith("/")||name.split("/").some(p=>p.startsWith(".")&&p!==".."))return;
  if(!isSafeZipEntryName(name)){aborted=true;rejectAll(new Error("ZIP contains an unsafe path; archive rejected."));return;}
  if(!/\.(jpe?g|png|webp)$/i.test(name))return;
  count++;if(count>MAX_FILES){aborted=true;rejectAll(new Error("ZIP contains more than 500 photos."));return;}
  let size=0;const chunks:Uint8Array[]=[];
  const task=new Promise<File>((resolve,reject)=>{
   entry.ondata=(err,chunk,final)=>{if(err){aborted=true;reject(err);return;}size+=chunk.length;total+=chunk.length;if(size>MAX_FILE_BYTES||total>MAX_BATCH_BYTES){aborted=true;const e=new Error("ZIP expanded beyond configured photo limits.");reject(e);rejectAll(e);return;}chunks.push(chunk);if(final){const filename=name.split("/").pop()||"photo";resolve(new File(chunks.map(chunk=>new Uint8Array(chunk).buffer as ArrayBuffer),filename,{type:""}));}};
  });
  promises.push(task);entry.start();
 });
 unzip.register(UnzipInflate);unzip.register(UnzipPassThrough);
 for(let offset=0;offset<bytes.length;offset+=1024*1024){if(aborted)break;unzip.push(bytes.subarray(offset,Math.min(bytes.length,offset+1024*1024)),offset+1024*1024>=bytes.length);}
 if(aborted)throw new Error("ZIP extraction stopped because the archive exceeded safety checks.");
 const files=await Promise.race([Promise.all(promises),failed]);
 if(!files.length)throw new Error("No supported JPEG, PNG, or WebP photos found in ZIP.");
 return files;
}
export function StudentPhotoWorkspace({projectId,initialPrefix=null}:{projectId:string;initialPrefix?:string|null}){
 const [workspace,setWorkspace]=useState<Workspace|null>(null);const [loading,setLoading]=useState(true);const [queue,setQueue]=useState<QueueItem[]>([]);const [busy,setBusy]=useState(false);const cancelRef=useRef(false);
 const [error,setError]=useState("");const [notice,setNotice]=useState("");const [search,setSearch]=useState("");const [filter,setFilter]=useState("ALL");const [studentSearch,setStudentSearch]=useState("");const [prefix,setPrefix]=useState(initialPrefix??"");const [dragging,setDragging]=useState(false);
 const refresh=useCallback(async()=>{try{const w=await loadPhotoWorkspace(projectId) as Workspace;setWorkspace(w);}catch(e){setError(e instanceof Error?e.message:"Could not load photo workspace.");}finally{setLoading(false);}},[projectId]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void refresh();},0);return()=>window.clearTimeout(timer);},[refresh]);
 const studentById=useMemo(()=>new Map((workspace?.students??[]).map(s=>[s.id,s])),[workspace]);
 const studentBySerial=useMemo(()=>new Map((workspace?.students??[]).map(s=>[String(s.serial_number),s])),[workspace]);
 const filteredPhotos=useMemo(()=>{const q=search.trim().toLowerCase();return(workspace?.photos??[]).filter(p=>(filter==="ALL"||p.match_status===filter)&&( !q||p.original_filename.toLowerCase().includes(q)||String(p.serial_number??p.normalized_serial_number??"").includes(q)||(p.student_id&&studentById.get(p.student_id)&&studentLabel(studentById.get(p.student_id)!).toLowerCase().includes(q))));},[workspace,filter,search,studentById]);
 const studentOptions=useMemo(()=>{const q=studentSearch.trim().toLowerCase();return(workspace?.students??[]).filter(s=>!q||studentLabel(s).toLowerCase().includes(q)||String(s.serial_number).includes(q));},[workspace,studentSearch]);
 async function acceptFiles(incoming:FileList|File[]|null,append=false){if(!incoming)return;setError("");setNotice("");let files=Array.from(incoming);try{const expanded:File[]=[];for(const f of files){if(/\.zip$/i.test(f.name)){expanded.push(...await extractZip(f));}else expanded.push(f);}if(expanded.length>MAX_FILES)throw new Error("A batch is limited to 500 images.");const unsupported=expanded.filter(f=>!imageMime(f));if(unsupported.length)throw new Error(unsupported.length+" unsupported file(s). Use JPEG, PNG or WebP.");if(expanded.some(f=>f.size<1||f.size>MAX_FILE_BYTES))throw new Error("Each image must be between 1 byte and 10 MB.");if(expanded.reduce((n,f)=>n+f.size,0)>MAX_BATCH_BYTES)throw new Error("Total batch size exceeds 500 MB.");const added=expanded.map((file,i)=>({id:(append?"camera-"+Date.now()+"-"+i+"-":"")+String(i)+"-"+file.name+"-"+file.size+"-"+file.lastModified,file,status:"queued" as const}));setQueue(old=>append?[...old,...added]:added);setNotice(expanded.length+" image files are ready for upload. Matching is by exact filename serial only.");}catch(e){setError(e instanceof Error?e.message:"Could not prepare these files.");}}
 async function runQueue(items:QueueItem[]){
  if(!items.length)return;setBusy(true);cancelRef.current=false;setError("");setNotice("");
  let batchId:string|null=null;let completed=0,failed=0;
  try{
   const totalBytes=items.reduce((n,i)=>n+i.file.size,0);if(totalBytes>MAX_BATCH_BYTES)throw new Error("Total batch size exceeds 500 MB.");
   const batch=await createPhotoBatch({projectId,totalCount:items.length,name:"Photo upload · "+new Date().toLocaleString()});batchId=batch.id;
   setQueue(old=>old.map(q=>items.some(i=>i.id===q.id)?{...q,status:"queued",message:undefined}:q));
   let next=0;
   const worker=async()=>{while(true){if(cancelRef.current)return;const idx=next++;if(idx>=items.length)return;const item=items[idx];setQueue(old=>old.map(q=>q.id===item.id?{...q,status:"uploading",message:undefined}:q));let path="";
    try{const mime=imageMime(item.file);const ticket=await createPhotoUploadTicket({projectId,batchId:batch.id,filename:item.file.name,size:item.file.size});path=ticket.path;const supabase=createClient();const {error:up}=await supabase.storage.from("printforge-student-photos").uploadToSignedUrl(path,ticket.token,item.file,{contentType:mime,upsert:false});if(up)throw new Error(up.message);const result=await registerStudentPhoto({projectId,batchId:batch.id,storagePath:path,originalFilename:item.file.name});completed++;setQueue(old=>old.map(q=>q.id===item.id?{...q,status:"uploaded",message:result.status}:q));
    }catch(e){failed++;const message=e instanceof Error?e.message:"Upload failed";setQueue(old=>old.map(q=>q.id===item.id?{...q,status:"failed",message}:q));if(path){try{await recordPhotoUploadFailure({projectId,batchId:batch.id,storagePath:path,filename:item.file.name,message,size:item.file.size});}catch{}}}
   }};
   await Promise.all(Array.from({length:Math.min(CONCURRENCY,items.length)},()=>worker()));
   const remaining=items.length-completed-failed;
   if(cancelRef.current){setQueue(old=>old.map(q=>items.some(i=>i.id===q.id)&&q.status==="queued"?{...q,status:"cancelled"}:q));setNotice("Upload cancelled. "+completed+" completed and "+failed+" failed; completed files were preserved.");}
   const summary=await finishPhotoBatch({projectId,batchId:batch.id,failedCount:failed+remaining});setNotice("Batch finished: "+summary.registered+" files recorded, "+summary.failed+" failed/invalid, "+summary.review+" needing review or matching.");await refresh();
  }catch(e){setError(e instanceof Error?e.message:"Photo upload failed.");}
  finally{setBusy(false);}
 }
 function cancel(){cancelRef.current=true;}
 async function assign(photo:Photo,studentId:string){setError("");setNotice("");try{const approved=workspace?.photos.find(p=>p.student_id===studentId&&p.match_status==="APPROVED"&&p.id!==photo.id);let replaceApproved=false;if(approved){if(!window.confirm("This student already has an approved photo. Replace it? The old photo will be kept for review."))return;replaceApproved=true;}const r=await assignStudentPhoto({projectId,photoId:photo.id,studentId:studentId||null,replaceApproved});setNotice("Photo assignment saved ("+r.status+").");await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not assign photo.");}}
 async function approve(photo:Photo){setError("");setNotice("");try{const existing=workspace?.photos.find(p=>p.student_id===photo.student_id&&p.match_status==="APPROVED"&&p.id!==photo.id);let replaceApproved=false;if(existing){if(!window.confirm("Replace the student's approved photo? The previous photo will remain available for review."))return;replaceApproved=true;}await approveStudentPhoto({projectId,photoId:photo.id,replaceApproved});setNotice("Photo approved for this student.");await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not approve photo.");}}
 async function savePrefix(){try{const r=await setPhotoSerialPrefix({projectId,prefix:prefix||null});setPrefix(r.prefix??"");setNotice(r.prefix?"Filename prefix enabled: "+r.prefix:"Filename prefix matching disabled.");}catch(e){setError(e instanceof Error?e.message:"Could not save prefix.");}}
 const activeQueue=queue.filter(q=>q.status==="queued"||q.status==="uploading").length;const completedQueue=queue.filter(q=>q.status==="uploaded").length;const failedQueue=queue.filter(q=>q.status==="failed").length;
 return <section id="student-photos" className="pf-panel mt-5 p-5">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm text-blue-300">PHASE 6</p><h2 className="text-xl font-bold">Student photos & serial matching</h2><p className="pf-muted mt-1 text-sm">Upload photos in bulk, match exact filename serials, then review and approve every student photo. No order-based matching.</p></div><div className="flex flex-wrap gap-2"><label className="inline-flex min-h-11 cursor-pointer items-center rounded-lg border border-white/15 px-4 py-2 text-sm font-medium">Choose photos / ZIP<input className="sr-only" type="file" multiple accept=".jpg,.jpeg,.png,.webp,.zip,image/jpeg,image/png,image/webp,application/zip" disabled={busy} onChange={e=>{void acceptFiles(e.target.files);e.currentTarget.value="";}}/></label><CameraCapture disabled={busy} onCapture={async file=>{await acceptFiles([file],true);}}/></div></div>
  <div onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);void acceptFiles(e.dataTransfer.files);}} className={"mt-4 rounded-xl border-2 border-dashed p-6 text-center "+(dragging?"border-blue-400 bg-blue-400/10":"border-white/15")}><p className="font-medium">Drag and drop photos or a ZIP archive here</p><p className="pf-muted mt-1 text-xs">JPEG, PNG, WebP · max 10 MB per image · max 500 images / 500 MB per batch · ZIP max 100 MB compressed</p></div>
  {error&&<p role="alert" className="mt-3 rounded-lg border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}{notice&&<p role="status" className="mt-3 rounded-lg border border-emerald-400/30 bg-emerald-400/10 p-3 text-sm text-emerald-200">{notice}</p>}
  {queue.length>0&&<div className="mt-4 rounded-xl border border-white/10 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Upload queue</h3><p className="pf-muted text-xs">{queue.length} files · {completedQueue} uploaded · {failedQueue} failed · {activeQueue} pending/in progress</p></div><div className="flex gap-2">{busy?<button className="rounded-lg border border-white/15 px-3 py-2 text-sm" onClick={cancel}>Cancel queued work</button>:<><button className="rounded-lg border border-white/15 px-3 py-2 text-sm" onClick={()=>void runQueue(queue.filter(q=>q.status==="failed"||q.status==="queued"||q.status==="cancelled"))} disabled={!queue.some(q=>q.status==="failed"||q.status==="queued"||q.status==="cancelled")}>Upload / retry</button><button className="rounded-lg border border-white/15 px-3 py-2 text-sm" onClick={()=>setQueue([])}>Clear queue</button></>}</div></div><div className="mt-3 max-h-48 space-y-2 overflow-auto">{queue.map(q=><div key={q.id} className="flex items-center justify-between gap-2 text-xs"><span className="min-w-0 truncate">{q.file.name}</span><span className={q.status==="failed"?"text-red-300":q.status==="uploaded"?"text-emerald-300":q.status==="uploading"?"text-blue-300":"pf-muted"}>{q.status}{q.message?" · "+q.message:""}</span></div>)}</div></div>}
  {loading?<p className="pf-muted mt-5 text-sm">Loading project photo records…</p>:workspace&&<>
   <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-8">{[["Students",workspace.summary.totalStudents],["Approved",workspace.summary.approvedPhotos],["Missing",workspace.summary.missingPhotos],["Unmatched",workspace.summary.unmatched],["Needs review",workspace.summary.needsReview],["Duplicate files",workspace.summary.duplicates],["Serial conflicts",workspace.summary.serialConflicts],["Failed/invalid",workspace.summary.failed]].map(([label,value])=><div key={String(label)} className="rounded-lg border border-white/10 p-3"><p className="pf-muted text-xs">{label}</p><p className="mt-1 text-xl font-semibold">{Number(value).toLocaleString()}</p></div>)}</div>
   <div className="mt-5 rounded-xl border border-white/10 p-4"><h3 className="font-semibold">Filename serial configuration</h3><p className="pf-muted mt-1 text-sm">Numeric filenames such as 001.jpg and 001_Rahul_Sharma.png are supported. A prefix such as STU-001 is matched only when you explicitly configure STU here.</p><div className="mt-3 flex flex-wrap gap-2"><input value={prefix} onChange={e=>setPrefix(e.target.value)} maxLength={16} placeholder="Optional prefix, e.g. STU" className="rounded-lg border border-white/15 bg-black/20 px-3 py-2 text-sm"/><button onClick={()=>void savePrefix()} className="rounded-lg border border-white/15 px-3 py-2 text-sm">Save prefix</button></div></div>
   <div className="mt-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">Photo matching review</h3><button onClick={async()=>{setBusy(true);setError("");setNotice("");try{const r=await processPhotoMatches(projectId);setNotice("Processed "+r.processed+" photos: "+r.matched+" exact matches, "+r.needsReview+" requiring review, "+r.unmatched+" unmatched, "+r.duplicates+" duplicate files.");await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not process photo matches.");}finally{setBusy(false);}}} disabled={busy||!workspace.photos.length} className="mt-2 rounded-lg border border-white/15 px-3 py-2 text-xs font-semibold disabled:opacity-40">Process / Match Photos</button></div><div className="flex flex-wrap gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search filename, student, serial…" className="min-w-48 rounded-lg border border-white/15 bg-black/20 px-3 py-2 text-sm"/><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-lg border border-white/15 bg-black/20 px-3 py-2 text-sm"><option value="ALL">All statuses</option>{["MATCHED","APPROVED","NEEDS_REVIEW","UNMATCHED","DUPLICATE","UPLOAD_FAILED","INVALID_FILE"].map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></div></div>
    {!filteredPhotos.length?<p className="pf-muted mt-3 rounded-lg border border-white/10 p-5 text-sm">No photo records match this filter. Upload photos to begin matching.</p>:<div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{filteredPhotos.map(p=>{const assigned=p.student_id?studentById.get(p.student_id):null;const suggested=!assigned&&p.normalized_serial_number?studentBySerial.get(p.normalized_serial_number):null;const target=assigned??suggested;const errors=Array.isArray(p.validation_errors)?p.validation_errors.filter(Boolean).join(" · "):"";return <article key={p.id} className="overflow-hidden rounded-xl border border-white/10"><div className="flex gap-3 p-3"><div className="flex h-24 w-20 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-white/5">{p.previewUrl?<img src={p.previewUrl} alt={p.original_filename} className="h-full w-full object-cover"/>:<span className="pf-muted text-xs">No preview</span>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{p.original_filename}</p><p className="pf-muted mt-1 text-xs">{p.width_px&&p.height_px?p.width_px+"×"+p.height_px+" · ":""}{p.file_size_bytes?Math.ceil(p.file_size_bytes/1024)+" KB":""}</p><p className="mt-2 text-xs font-semibold">{p.match_status.replaceAll("_"," ")}</p>{p.original_serial_number&&<p className="pf-muted mt-1 text-xs">Filename serial: {p.original_serial_number}</p>}{p.duplicate_of_id&&<p className="mt-1 text-xs text-amber-300">Duplicate of another uploaded file</p>}{errors&&<p className="mt-1 text-xs text-amber-200">{errors}</p>}</div></div>
    <div className="border-t border-white/10 p-3"><p className="text-xs font-medium">{assigned?"Assigned: "+studentLabel(assigned):suggested?"Proposed: "+studentLabel(suggested):"No student assigned"}</p><label className="mt-2 block text-xs pf-muted">Assign / change student</label><select value={p.student_id??""} onChange={e=>void assign(p,e.target.value)} className="mt-1 w-full rounded-lg border border-white/15 bg-black/20 px-2 py-2 text-xs"><option value="">Unassigned</option>{studentOptions.map(s=><option key={s.id} value={s.id}>{studentLabel(s)}</option>)}</select><input value={studentSearch} onChange={e=>setStudentSearch(e.target.value)} placeholder="Filter student list…" className="mt-2 w-full rounded-lg border border-white/15 bg-black/20 px-2 py-1.5 text-xs"/><div className="mt-2 flex flex-wrap gap-2">{p.match_status!=="APPROVED"&&p.student_id&&<button onClick={()=>void approve(p)} className="rounded-md bg-blue-500 px-3 py-1.5 text-xs font-semibold text-white">Confirm / approve</button>}{p.student_id&&<button onClick={()=>void assign(p,"")} className="rounded-md border border-white/15 px-3 py-1.5 text-xs">Clear assignment</button>}</div></div></article>;})}</div>}
   </div>
   <div className={"mt-5 rounded-xl border p-4 "+(workspace.summary.missingPhotos===0&&workspace.summary.unmatched===0&&workspace.summary.needsReview===0&&workspace.summary.duplicates===0&&workspace.summary.serialConflicts===0&&workspace.summary.failed===0?"border-emerald-400/30":"border-amber-400/30")}><h3 className="font-semibold">Photo readiness: {workspace.summary.missingPhotos===0&&workspace.summary.unmatched===0&&workspace.summary.needsReview===0&&workspace.summary.duplicates===0&&workspace.summary.failed===0?"READY":"NOT READY"}</h3><p className="pf-muted mt-1 text-xs">All students need approved photos and no unresolved upload, duplicate, unmatched, or review states.</p></div><div className="mt-5 rounded-xl border border-white/10 p-4"><h3 className="font-semibold">Recent upload batches</h3>{workspace.batches.length?<div className="mt-2 space-y-2">{workspace.batches.map(b=><div key={b.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-white/10 py-2 text-xs"><span>{b.name} · {new Date(b.created_at).toLocaleString()}</span><span>{b.completed_count}/{b.total_count} recorded · {b.failed_count} failed · {b.review_count} review · {b.status}</span></div>)}</div>:<p className="pf-muted mt-2 text-sm">No upload batches yet.</p>}<p className="pf-muted mt-3 text-xs">Only APPROVED photos count toward readiness. A project is ready for the next phase only after every intended student has an approved photo and no review/duplicate conflicts remain.</p></div>
  </>}
 </section>;
}
