"use client";
import { useRef, useState } from "react";
import { createTemplatePreview, deleteTemplate, uploadTemplate } from "@/app/dashboard/actions";
import { STORAGE_BUCKETS } from "@/lib/supabase/storage";
type Template={id:string;name:string;source_path:string|null;source_type:string;width_px:number|null;height_px:number|null;analysis_status:string;version_number:number;is_active:boolean;created_at:string};
export function TemplateWorkspace({projectId,templates}:{projectId:string;templates:Template[]}){
 const input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false),[error,setError]=useState(""),[preview,setPreview]=useState<string|null>(null),[previewType,setPreviewType]=useState<string>("");
 const active=templates.find(t=>t.is_active)??templates[0];
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setBusy(true);setError("");try{await uploadTemplate({projectId,file:f});location.reload()}catch(e){setError(e instanceof Error?e.message:"Template upload failed")}finally{setBusy(false);e.target.value=""}}
 async function openPreview(t:Template){if(!t.source_path)return;setError("");try{setPreviewType(t.source_type);setPreview(await createTemplatePreview({bucket:STORAGE_BUCKETS.templates,path:t.source_path}))}catch(e){setError(e instanceof Error?e.message:"Preview unavailable")}}
 async function remove(t:Template){if(!confirm("Delete this template version?"))return;setBusy(true);setError("");try{await deleteTemplate({projectId,templateId:t.id});location.reload()}catch(e){setError(e instanceof Error?e.message:"Delete failed")}finally{setBusy(false)}}
 return <div className="space-y-5"><div className="pf-panel p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">ID-card template</h2><p className="pf-muted mt-1 text-sm">Upload a PNG, JPEG, sanitized SVG, or single-page PDF. The original is kept private in Supabase Storage.</p></div><button className="pf-button" disabled={busy} onClick={()=>input.current?.click()}>{busy?"Working…":active?"Replace template":"Upload template"}</button><input ref={input} hidden type="file" accept="image/png,image/jpeg,image/svg+xml,application/pdf,.png,.jpg,.jpeg,.svg,.pdf" onChange={upload}/></div>{error&&<div className="mt-4 rounded-lg border border-red-900 bg-red-950/40 p-3 text-sm text-red-200">{error}</div>}{active?<div className="mt-6 overflow-hidden rounded-xl border border-slate-800 bg-black/30"><div className="flex items-center justify-between border-b border-slate-800 px-4 py-3 text-sm"><span>Version {active.version_number} · {active.width_px}×{active.height_px}px</span><span className="text-emerald-300">Active</span></div><button className="block w-full cursor-zoom-in p-3" onClick={()=>openPreview(active)}>{preview&&(active.source_type==="pdf"?<iframe src={preview} title="PDF ID-card template preview" className="mx-auto h-[75vh] w-full border-0"/>:<img src={preview} alt="ID-card template preview" className="mx-auto max-h-[75vh] w-auto max-w-full object-contain"/>)}{!preview&&<div className="flex min-h-80 items-center justify-center text-slate-500">Click to load full-resolution preview</div>}</button></div>:<div className="mt-6 rounded-xl border border-dashed border-slate-700 p-12 text-center text-slate-500">No template uploaded yet.</div>}</div><div className="pf-panel p-6"><h3 className="font-bold">Saved versions</h3><div className="mt-4 space-y-2">{templates.map(t=><div key={t.id} className="flex items-center justify-between gap-3 rounded-lg border border-slate-800 p-3"><div><div className="font-medium">Version {t.version_number} · {t.name}</div><div className="pf-muted text-xs mt-1">{t.width_px}×{t.height_px}px · {t.analysis_status}</div></div><div className="flex gap-2">{t.source_path&&<button className="pf-button-secondary text-xs" onClick={()=>openPreview(t)}>Preview</button>}<button className="pf-button-secondary text-xs" disabled={busy} onClick={()=>remove(t)}>Delete</button></div></div>)}</div></div>{preview&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4" onClick={()=>setPreview(null)}>{previewType==="pdf"?<iframe src={preview} title="PDF ID-card template preview" className="h-[95vh] w-[95vw] border-0" onClick={e=>e.stopPropagation()}/>:<img src={preview} alt="ID-card template preview" className="max-h-[95vh] max-w-[95vw] object-contain" onClick={e=>e.stopPropagation()}/>}<button className="absolute right-5 top-5 rounded-full bg-white/10 px-4 py-2 text-white">Close</button></div>}</div>
}